name: syag
description: SYAG APP.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  # for svg images
  flutter_svg: ^0.22.0
  # for make app responsive
  sizer: ^2.0.15
  shared_preferences: ^2.0.8
  get: ^4.3.8
  # dio: ^4.0.0 
  fluttertoast: ^8.0.8
  # persistent_bottom_nav_bar: ^4.0.2
  # email_validator: ^2.0.1
  # flutter_html: ^2.1.2
  flutter_countdown_timer: ^4.1.0
  # url_launcher: ^6.0.11
  intl: ^0.17.0
  carousel_pro_nullsafety: ^1.0.2
  # buttons_tabbar: ^1.3.1
  share: ^2.0.4
  # onesignal_flutter: ^3.2.4
  # flutter_ringtone_player: ^3.1.0
  pin_code_fields: ^7.3.0
  flutter_spinkit: ^5.0.0
  # device_preview: ^1.0.0
  flutter_hooks: ^0.18.1
  dartz: ^0.10.1
  freezed_annotation: ^0.14.1
  # flutter_datetime_picker: ^1.5.1 
  image_picker: ^0.8.4+4
  step_progress_indicator: ^1.0.1
  flutter_image_slideshow: ^0.1.2
  scrollable_positioned_list: ^0.2.3
  carousel_slider: ^4.0.0
  file_picker: ^4.2.7
  # keyboard_attachable: ^2.1.0
  http: ^0.13.4
  json_annotation: ^4.3.0

  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master
  
  introduction_screen: 
     git:
       url: https://github.com/mariamalbarghouti/introduction_screen_modification.git
       ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: 
  freezed: ^0.14.1+1
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900
          
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
